version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
        volumes:
            - ./data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        environment:
           elasticsearch_yml: |
               network.host: 0.0.0.0
               http.cors.enabled: true
               http.cors.allow-origin: "*"
               xpack.security.enabled: false
               
